Continuing from the median task, Now see the merge.csv data and groupby the questions by concepts.
If a specific concept has 7 qs, then continue the code as from median_task.

In [1]:
import pandas as pd
import numpy as np
import os
os.chdir("D:/iAnalyst/MyPat task")

In [2]:
df=pd.read_csv("merge.csv",index_col='Unnamed: 0')  #Excluding the unrequired column

In [3]:
data=df.copy()

In [4]:
data= data.drop_duplicates()   #There are duplicates in the data. Removing them
data.reset_index(inplace=True)   #Adjusting the indices accordingly as after removing duplicates the indices get distorted

In [5]:
data.drop('index',axis=1,inplace=True)    #Dropping the current index as no need now.

In [6]:
data

,Enrolment No,AIR,Question ID,Mapped Master Concept,Response,b,a,c,p,theta,p_theta
0,1.112580e+12,12087,5a8ad03c738197281fba6578,5ace20419fe7b01d5806c1d6,0,1.859200,1.001975,0.150116,0.8,1.386294,0.673893
1,1.112580e+12,12087,5a8ad03a738197281fba64d9,5ace20419fe7b01d5806c1d6,1,0.195881,0.994663,0.149227,0.8,1.386294,0.348582
2,1.112580e+12,12087,5ab2164decf0ff301334ea28,5ace20419fe7b01d5806c1d6,1,-0.365478,0.926349,0.112355,0.8,1.386294,0.258662
3,1.112580e+12,12087,5ab2164decf0ff301334ea2c,5ace20419fe7b01d5806c1d6,1,-0.354866,0.926573,0.113871,0.8,1.386294,0.261083
4,1.112580e+12,12087,5a8ad040738197281fba6713,5ace20419fe7b01d5806c1d6,1,-0.305276,0.927603,0.117638,0.8,1.386294,0.269708
...,...,...,...,...,...,...,...,...,...,...,...
442,1.112580e+12,12087,5a8ad041738197281fba67bd,5ace203d9fe7b01d5806c078,0,0.301507,1.002358,0.149863,0.0,-4.000000,0.988749
443,1.112580e+12,12087,5ab2164decf0ff301334eac4,5ace20399fe7b01d5806bf41,1,0.170115,0.962336,0.142449,1.0,4.000000,0.163431
444,1.112580e+12,12087,5a8ad041738197281fba67bf,5ace203d9fe7b01d5806c07e,1,-0.116233,0.933674,0.129452,1.0,4.000000,0.147711
445,1.112580e+12,12087,5a8ad034738197281fba63eb,5ace203d9fe7b01d5806c09a,1,0.208473,0.973714,0.145373,1.0,4.000000,0.166157
446,1.112580e+12,12087,5a8ad041738197281fba67c5,5ace20399fe7b01d5806bf66,1,0.182681,0.989607,0.148775,1.0,4.000000,0.167813

In [7]:
data.columns

Index(['Enrolment No', 'AIR', 'Question ID', 'Mapped Master Concept',
       'Response', 'b', 'a', 'c', 'p', 'theta', 'p_theta'],
      dtype='object')

In [8]:
#c= input("Please enter the master mapped concept: ")   #5a8ad034738197281fba63eb

In [9]:
data=data.sort_values(by='p_theta')

In [10]:
c1= data[data["Mapped Master Concept"]=='5ace203a9fe7b01d5806bf7b']
c1.reset_index(drop=True, inplace=True) 
#c1= c1.drop(columns= ['level_0','index'])
c1

,Enrolment No,AIR,Question ID,Mapped Master Concept,Response,b,a,c,p,theta,p_theta
0,1.112580e+12,12087,5a8ad041738197281fba67c1,5ace203a9fe7b01d5806bf7b,1,-0.359199,0.926487,0.113492,0.625,0.510826,0.387183
1,1.112580e+12,12087,5a8ad041738197281fba67a3,5ace203a9fe7b01d5806bf7b,1,-0.242599,0.929113,0.121855,0.625,0.510826,0.413231
2,1.112580e+12,12087,5a8ad041738197281fba67c3,5ace203a9fe7b01d5806bf7b,0,0.193972,0.986575,0.148272,0.625,0.510826,0.508110
3,1.112580e+12,12087,5a8ad03e738197281fba66dc,5ace203a9fe7b01d5806bf7b,1,0.431638,1.004635,0.149874,0.625,0.510826,0.558038
4,1.112580e+12,12087,5ab2164decf0ff301334eaa2,5ace203a9fe7b01d5806bf7b,1,0.505398,1.005725,0.149881,0.625,0.510826,0.573780
5,1.112580e+12,12087,5a8ad041738197281fba67b9,5ace203a9fe7b01d5806bf7b,1,0.552583,1.006349,0.149885,0.625,0.510826,0.583872
6,1.112580e+12,12087,5a8ad03c738197281fba6632,5ace203a9fe7b01d5806bf7b,0,0.652840,1.007490,0.149896,0.625,0.510826,0.605304
7,1.112580e+12,12087,5a8ad03a738197281fba654b,5ace203a9fe7b01d5806bf7b,0,1.471795,1.007771,0.150031,0.625,0.510826,0.766095

In [11]:
#sorting
#c1.sort_values(by='p_theta')
#c1

In [12]:
if (len(c1)%2==0):
    m1= c1.p_theta.iloc[(len(c1)//2)-1]
else:
    m1= c1[c1['p_theta']==c1['p_theta'].median()]
m1

0.558038052

In [13]:
med= c1[c1['p_theta']==m1]
med

,Enrolment No,AIR,Question ID,Mapped Master Concept,Response,b,a,c,p,theta,p_theta
3,1.112580e+12,12087,5a8ad03e738197281fba66dc,5ace203a9fe7b01d5806bf7b,1,0.431638,1.004635,0.149874,0.625,0.510826,0.558038

In [14]:
while len(c1)>=1:    #if len more than 1 then their median can be caluclated
    n= int(input("Enter 0 to increment or 1 to decrement : "))
    
    if n==1:
        if bool(c1['p_theta'].median())==True:    #This loop is to ensure that when the medians will get over (i.e. the questions at one median end(e.g.easy qs)) the loop stops
            #display((data.iloc[med.index-1]))
            #display((data.iloc[med.index]))
            display((c1.iloc[med.index+1]))         #printing the next in line question
        
            c1=c1.drop(med.index,axis=0)     #deleting the current median
            c1= c1.reset_index(drop= True)       #drop=true is imp as without it the previous indices keep piling up and code doesn't work as it cannot find next medians acc to indices
            if med.index==len(c1)-1:                              #because the loop wasnt ending.
                print('stop1!!')
                break
        else:
            break
        

    elif n==0:
        if bool(c1['p_theta'].median())==True:
            display((c1.iloc[med.index-1]))
            #display((data.iloc[med.index]))
            #display((data.iloc[med.index+1]))
        
            c1=c1.drop(med.index-1,axis=0)    #Here med.index-1 is imp as we have to get the previous index since we are moving from 70 to 69. In above n==0 case the median automatically goes to the next possible value
            c1= c1.reset_index(drop= True)
            med.index=med.index-1                         #Same reason as above
            
            if med.index==0:                              #because the loop wasnt ending.
                print('stop0!!')
                break
        else:
            break
    
        
    else:    
        print("Enter a valid number")
        break

Enter 0 to increment or 1 to decrement : 0

,Enrolment No,AIR,Question ID,Mapped Master Concept,Response,b,a,c,p,theta,p_theta
2,1.112580e+12,12087,5a8ad041738197281fba67c3,5ace203a9fe7b01d5806bf7b,0,0.193972,0.986575,0.148272,0.625,0.510826,0.50811

Enter 0 to increment or 1 to decrement : 0

,Enrolment No,AIR,Question ID,Mapped Master Concept,Response,b,a,c,p,theta,p_theta
1,1.112580e+12,12087,5a8ad041738197281fba67a3,5ace203a9fe7b01d5806bf7b,1,-0.242599,0.929113,0.121855,0.625,0.510826,0.413231

Enter 0 to increment or 1 to decrement : 0

,Enrolment No,AIR,Question ID,Mapped Master Concept,Response,b,a,c,p,theta,p_theta
0,1.112580e+12,12087,5a8ad041738197281fba67c1,5ace203a9fe7b01d5806bf7b,1,-0.359199,0.926487,0.113492,0.625,0.510826,0.387183

stop0!!

In [15]:
med.index[0]

0

In [16]:
c1.iloc[167]

IndexError: single positional indexer is out-of-bounds

In [ ]:
#len(c1)==len(c1)//2

In [ ]:
(c1[(len(c1) - 1) / 2] + c1[len(c1) / 2]) / 2.0

In [ ]:
#data.iloc[med.index]

In [ ]:
#data.iloc[med.index]
#data.drop(med.index,axis=0)